package/procps-ng: security bump to version 4.0.4
- Fixes CVE-2023-4016

- Drop all patches (already in version) and so also drop autoreconf

- This bump will also fix the following build failure with gcc >= 14:

  pgrep.c: In function 'main':
  pgrep.c:1066:37: error: implicit declaration of function 'pidfd_open'; did you mean 'fdopen'? [-Wimplicit-function-declaration]
   1066 |                         int pidfd = pidfd_open(procs[i].num, 0);
        |                                     ^~~~~~~~~~
        |                                     fdopen

https://gitlab.com/procps-ng/procps/-/blob/v4.0.4/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/bd7b49123905c580842a3dd3b7a338d5aedf55d7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
(cherry picked from commit d79f40dbbe98983bc657d4c82d46b38b8283351b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>